apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJib25hdmFkZXVyIiwicGFzc3dvcmQiOiJkY2tyX3BhdF85ejJPZTAtUkNSR2pHaGxkQjRwX1RPcDJRczQiLCJlbWFpbCI6ImRhb2RhaWhpZXAyMnVzc3JAZ21haWwuY29tIiwiYXV0aCI6IlltOXVZWFpoWkdWMWNqcGtZMnR5WDNCaGRGODVlakpQWlRBdFVrTlNSMnBIYUd4a1FqUndYMVJQY0RKUmN6UT0ifX19
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"Secret","apiVersion":"v1","metadata":{"name":"shuka-private","creationTimestamp":null},"data":{".dockerconfigjson":"eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJib25hdmFkZXVyIiwicGFzc3dvcmQiOiJkY2tyX3BhdF85ejJPZTAtUkNSR2pHaGxkQjRwX1RPcDJRczQiLCJlbWFpbCI6ImRhb2RhaWhpZXAyMnVzc3JAZ21haWwuY29tIiwiYXV0aCI6IlltOXVZWFpoWkdWMWNqcGtZMnR5WDNCaGRGODVlakpQWlRBdFVrTlNSMnBIYUd4a1FqUndYMVJQY0RKUmN6UT0ifX19"},"type":"kubernetes.io/dockerconfigjson"}
  name: shuka-private
  namespace: default
type: kubernetes.io/dockerconfigjson
